name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  ACR_IMAGE: ${{ vars.ACR_NAME }}.azurecr.io/java-demoapp:latest

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Azure
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Install Docker
    - name: Install Docker
      run: |
        sudo apt update && sudo apt install --no-install-recommends -y ca-certificates curl gnupg lsb-release
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update && sudo apt install --no-install-recommends -y docker-ce docker-ce-cli containerd.io

    # Step 4: Build Docker image
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az acr login --name ${{ vars.ACR_NAME }}

    - name: Build Docker Image
      run: |
        docker build -t $ACR_IMAGE .

    # Step 5: Push Docker image to Azure Container Registry
    - name: Push Docker Image to ACR
      run: |
        docker push $ACR_IMAGE

  # deploy:
  #   name: Deploy to Dev
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: development
  #   steps:
  #   # Step 1: Log in to Azure
  #   - name: Log in to Azure
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   # Step 2: Get AKS kubeconfig
  #   - name: Get AKS Kubeconfig
  #     run: |
  #       az aks get-credentials --resource-group ${{ AKS_RESOURCE_GROUP }} --name ${{ AKS_CLUSTER_NAME }} --overwrite-existing

  #   # Step 3: Deploy to Kubernetes
  #   - name: Deploy to Kubernetes
  #     run: |
  #       kubectl apply -f k8s/deployment.yaml
  #       kubectl apply -f k8s/service.yaml